version: "3.9"

services:

  devopsdb:
    image: akshithjanagam/automation:db
    deploy:
      replicas: 1
    networks:
      - Akshnetwork

  application:
    image: akshithjanagam/automation:app
    ports:
      - "1111:8080"
    deploy:
      replicas: 6
    networks:
      - Akshnetwork
    depends_on:
      - devopsdb

networks:
  Akshnetwork:
    driver: overlay
